"""added urls

Revision ID: 46cc619f93cb
Revises: af3b53cd9423
Create Date: 2025-07-21 19:45:38.480636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cc619f93cb'
down_revision: Union[str, Sequence[str], None] = 'af3b53cd9423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('youtube_url', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'youtube_url')
    # ### end Alembic commands ###
